name: template
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # MV
  provider: ^6.0.2

  # UI
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.3.1
  oktoast: ^3.1.5

  # GENERATORS
  auto_route: ^3.2.4
  paddinger: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # GENERATORS
  auto_route_generator: ^3.2.3
  paddinger_annotations: ^0.2.0

  # flutter packages pub run build_runner watch
  build_runner:

  # pub global run rename --bundleId com.example.appName
  # pub global run rename --appname "App name"
  rename:

flutter:
  uses-material-design: true
